### ISSUE TITLE
The tests do not run anymore

### ISSUE THREAD

**Issue by micheles** [gem/oq-risk-tests#24]
Here is the error:

Traceback (most recent call last):
  File "bin/oq-engine", line 44, in <module>
    from openquake.engine import utils, config
  File "/home/ubuntu/oq-engine/openquake/engine/utils/__init__.py", line 20, in <module>
    from openquake.baselib.performance import Monitor
  File "/home/ubuntu/oq-hazardlib/openquake/baselib/performance.py", line 24, in <module>
    import h5py
ImportError: No module named h5py

**Comment by daniviga** [comment]
Superseded by #25
